sudo: required
services:
    - docker
    
before_install:
    - docker build -t anilnair.n/docker-react -f Dockerfile.dev .
        
script:
    - docker run  -e CI=true anilnair.n/docker-react npm run test
    